// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type List struct {
	ID        int32
	Title     string
	UserID    pgtype.Int4
	Status    string
	CreatedAt pgtype.Timestamptz
}

type ListItem struct {
	ID        int32
	Title     string
	Unit      string
	Price     int32
	ListID    pgtype.Int4
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID             int32
	Name           string
	Email          string
	HashedPassword string
	CreatedAt      pgtype.Timestamp
}
