// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createList = `-- name: CreateList :one
INSERT INTO
    list (title, user_id, status)
VALUES ($1, $2, 'pending') RETURNING id, title, user_id, status, created_at
`

type CreateListParams struct {
	Title  string
	UserID pgtype.Int4
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (List, error) {
	row := q.db.QueryRow(ctx, createList, arg.Title, arg.UserID)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (
        name,
        email,
        hashed_password,
        created_at
    )
VALUES ($1, $2, $3, NOW()) RETURNING id, name, email, created_at
`

type CreateUserParams struct {
	Name           string
	Email          string
	HashedPassword string
}

type CreateUserRow struct {
	ID        int32
	Name      string
	Email     string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.HashedPassword)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, name, email, created_at FROM users
`

type ListAllUsersRow struct {
	ID        int32
	Name      string
	Email     string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) ListAllUsers(ctx context.Context) ([]ListAllUsersRow, error) {
	rows, err := q.db.Query(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUsersRow
	for rows.Next() {
		var i ListAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
